# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b83f71fae506fd71b7f2c2b880d2402f"
name = "multi-location-analytics"
application_url = "https://shopify.curetshop.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_locations,read_orders,read_analytics,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [ "https://shopify.curetshop.com/auth/callback" ]
